title:              Hans Nusspickel
email:              f/mwkdrdgo
description:        Computer Science Student | Graphics & Simulation Enthusiast
author:             Hans Nusspickel
# baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://hanusspi.github.io"

# Social Profiles
# twitter_username:   SBootstrap
github_username:    hanusspi
# facebook_username:  StartBootstrap
# instagram_username:
# linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
paginate:           5
paginate_path:      "/blog/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/
    sort_by: date

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  # - jekyll-latex  # Temporarily disabled locally - GitHub Pages will enable it
  - jekyll-redirect-from
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false
# kramdown:
#    input: GFM
#    syntax_highlighter: rouge